name: rawdah
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.3.0+4

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  audio_session: ^0.1.18
  audioplayers: ^2.0.0
  cloud_firestore: ^4.3.1
  cloud_functions: ^4.0.7
  figma_squircle: ^0.5.3
  firebase_app_check: ^0.1.1+8
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  firebase_storage: ^11.0.10
  firespeed: ^1.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  flutter_svg: ^1.1.6
  go_router: ^5.1.1
  google_sign_in: ^5.4.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  purchases_flutter: ^6.5.0
  share_plus: ^6.3.0
  shared_preferences: ^2.0.16
  url_launcher: ^6.1.7
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/audio/
    - assets/images/
    - assets/icons/

  fonts:
    - family: ScheherazadeNew
      fonts:
        - asset: fonts/ScheherazadeNew-Regular.ttf
          weight: 500
        - asset: fonts/ScheherazadeNew-Bold.ttf
          weight: 700
    - family: SofiaSans
      fonts:
        - asset: fonts/SofiaSans-Thin.ttf
          weight: 100
        - asset: fonts/SofiaSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/SofiaSans-ExtraLight.ttf
          weight: 200
        - asset: fonts/SofiaSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/SofiaSans-Light.ttf
          weight: 300
        - asset: fonts/SofiaSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/SofiaSans-Regular.ttf
          weight: 400
        - asset: fonts/SofiaSans-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/SofiaSans-Medium.ttf
          weight: 500
        - asset: fonts/SofiaSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/SofiaSans-SemiBold.ttf
          weight: 600
        - asset: fonts/SofiaSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/SofiaSans-Bold.ttf
          weight: 700
        - asset: fonts/SofiaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/SofiaSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/SofiaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/SofiaSans-Black.ttf
          weight: 900
        - asset: fonts/SofiaSans-BlackItalic.ttf
          weight: 900
          style: italic
