// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1wcQSr7pLM8BMfx3C4KkNxUcaKPzR5mY',
    appId: '1:808376571033:web:75c9ed30d191976e03d408',
    messagingSenderId: '808376571033',
    projectId: 'rawdah-5bcee',
    authDomain: 'rawdah-5bcee.firebaseapp.com',
    storageBucket: 'rawdah-5bcee.appspot.com',
    measurementId: 'G-ZHGM9KZ2LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgsRCmPtE5YUOWKSdlpAOZDQl3lEE0JGY',
    appId: '1:808376571033:android:eb4c690d4d0d5f7303d408',
    messagingSenderId: '808376571033',
    projectId: 'rawdah-5bcee',
    storageBucket: 'rawdah-5bcee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1ppM7VcIhzGWK-hjPWW_q3fVqmOqQNfo',
    appId: '1:808376571033:ios:3f1277e3452c402a03d408',
    messagingSenderId: '808376571033',
    projectId: 'rawdah-5bcee',
    storageBucket: 'rawdah-5bcee.appspot.com',
    iosClientId: '808376571033-nh11fpd5ck63g7afoualis1s0nn0g964.apps.googleusercontent.com',
    iosBundleId: 'io.startcode.rawdah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1ppM7VcIhzGWK-hjPWW_q3fVqmOqQNfo',
    appId: '1:808376571033:ios:e5bbd718c5d7738c03d408',
    messagingSenderId: '808376571033',
    projectId: 'rawdah-5bcee',
    storageBucket: 'rawdah-5bcee.appspot.com',
    iosClientId: '808376571033-2u3mr3jd222n6mnn62fmmjf1ofrn1289.apps.googleusercontent.com',
    iosBundleId: 'com.example.rawdah',
  );
}
